export const SET_AUDIO_CONTEXT = "SET_AUDIO_CONTEXT";
export const SET_OSC = "SET_OSC";
export const SET_VOICE_PAN = "SET_VOICE_PAN";
export const CHANGE_VOICES = "CHANGE_VOICES";
export const CHANGE_DETUNE = "CHANGE_DETUNE";
export const SET_WAVETABLE = "SET_WAVETABLE";
export const CHANGE_WAVE_TABLE_POSITION = "CHANGE_WAVE_TABLE_POSITION";
export const SET_AUDIO_FILE_REQUEST = "SET_AUDIO_FILE_REQUEST";
export const SET_AUDIO_FILE_SUCCESS = "SET_AUDIO_FILE_SUCCESS";
export const SET_AUDIO_FILE_ERROR = "SET_AUDIO_FILE_ERROR";

export type ActionTypes =
  | "SET_OSC"
  | "SET_VOICE_PAN"
  | "CHANGE_WAVE_TABLE_POSITION"
  | "SET_AUDIO_CONTEXT"
  | "CHANGE_VOICES"
  | "CHANGE_DETUNE"
  | "SET_WAVETABLE"
  | "SET_AUDIO_FILE_REQUEST"
  | "SET_AUDIO_FILE_SUCCESS"
  | "SET_AUDIO_FILE_ERROR";
