export const SET_IS_PLAYING = "SET_IS_PLAYING";
export const SET_VOICE_PAN = "SET_VOICE_PAN";
export const SET_WAVETABLE = "SET_WAVETABLE";
export const SET_CURRENT_WAVE = "SET_CURRENT_WAVE";
export const CHANGE_FREQUENCY_BIN = "CHANGE_FREQUENCY_BIN";
export const CHANGE_WAVE_TABLE_POSITION = "CHANGE_WAVE_TABLE_POSITION";
export const SET_AUDIO_FILE_REQUEST = "SET_AUDIO_FILE_REQUEST";
export const SET_AUDIO_FILE_SUCCESS = "SET_AUDIO_FILE_SUCCESS";
export const SET_AUDIO_FILE_ERROR = "SET_AUDIO_FILE_ERROR";

export type ActionTypes =
  | "SET_IS_PLAYING"
  | "SET_VOICE_PAN"
  | "CHANGE_WAVE_TABLE_POSITION"
  | "SET_AUDIO_CONTEXT"
  | "SET_WAVETABLE"
  | "SET_CURRENT_WAVE"
  | "CHANGE_FREQUENCY_BIN"
  | "SET_AUDIO_FILE_REQUEST"
  | "SET_AUDIO_FILE_SUCCESS"
  | "SET_AUDIO_FILE_ERROR";
