export const SET_AUDIO_CONTEXT = "SET_AUDIO_CONTEXT";
export const SET_OSC = "SET_OSC";
export const CHANGE_VOICES = "CHANGE_VOICES";
export const CHANGE_DETUNE = "CHANGE_DETUNE";
export const CHANGE_WAVE_TABLE_POSITION = "CHANGE_WAVE_TABLE_POSITION";

export type ActionTypes =
  | "SET_OSC"
  | "CHANGE_WAVE_TABLE_POSITION"
  | "SET_AUDIO_CONTEXT"
  | "CHANGE_VOICES"
  | "CHANGE_DETUNE";
